AWSTemplateFormatVersion: 2010-09-09
Description: Network Stack.
Outputs:
  Name:
    Description: Stack Name
    Export:
      Name: !Sub ${AWS::StackName}-Name
    Value: !Ref AWS::StackName
Parameters:
  CodeBucket:
    Description: CodeBucket.
    Type: String
    Default: bryanlabs-public
  CodeKey:
    Description: Key
    Type: String
    Default: bryanlabs.net_files/blog/ec2zoneids/ec2ZoneIds.zip
  LayerKey:
    Description: Key
    Type: String
    Default: bryanlabs.net_files/blog/ec2zoneids/boto3cloudformation.zip
  boto3cloudformationObjectVersion:
    Description: Lambda Layer containing updated boto3 with Cloudformation Helpers.
    Type: String
    Default: fJsFS8EIIZ4yo3rsPAV5HCMo4En3kDzU
  ec2ZoneIdsObjectVersion:
    Description: ec2ZoneIdsObjectVersion.
    Type: String
    Default: YIn6Tbs6bZ4Ff7UoJozMQZ6MfWW0JofH
Resources:
  myLambdaLayerboto3cloudformation:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      CompatibleRuntimes: 
        - python3.6
      Content: 
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref LayerKey
        S3ObjectVersion: !Ref boto3cloudformationObjectVersion
      Description: boto3cloudformation
      LayerName: boto3cloudformation
  ec2ZoneIdsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: ManageEvents
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - events:PutRule
            - events:DeleteRule
            - events:PutTargets
            - events:RemoveTargets
            - lambda:AddPermission
            - lambda:RemovePermission
            Resource: "*"
      - PolicyName: ManageRoutes
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ec2:DescribeAvailabilityZones
            - ssm:PutParameter
            - ssm:DeleteParameter
            Resource: "*"
      - PolicyName: WriteToCloudWatch
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            Resource: "*"
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
  ec2ZoneIds:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey
        S3ObjectVersion: !Ref ec2ZoneIdsObjectVersion
      Handler: index.lambda_handler
      MemorySize: 2048
      Role:
        Fn::GetAtt:
        - ec2ZoneIdsRole
        - Arn
      Runtime: python3.6
      Timeout: 900
      Layers:
      - !Ref myLambdaLayerboto3cloudformation
  ec2ZoneIdsExecution:
    Type: AWS::CloudFormation::CustomResource
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt ec2ZoneIds.Arn